#!/usr/bin/ruby

require_relative 'lib/blog'

POST_HTML = 'public/html/post_form.html'
INDEX = 'public/index.html'

root = './public/css'
port = 8000
address = 'localhost'

server = HTTPServer.new(:Port => port, :BindAddress => address, :DocumentRoot => root)
server.mount_proc('/post') { |req, res| res.body = File.read(POST_HTML) }
server.mount_proc('/') { |req, res| res.body = File.read(INDEX) }
#server.mount('/', Blog::Index)
trap("INT"){ server.shutdown }
server.start
